"""changed field types

Revision ID: 13f48dce5c72
Revises: a297269a8ec2
Create Date: 2023-07-15 18:25:36.860755

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '13f48dce5c72'
down_revision = 'a297269a8ec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
