"""create_tables

Revision ID: a297269a8ec2
Revises: c7c2f0cd2b55
Create Date: 2023-07-15 16:11:12.900165

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a297269a8ec2'
down_revision = 'c7c2f0cd2b55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Decimal_number', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('Product', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('Product', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('Product', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('Product', sa.Column('pid', postgresql.UUID(), nullable=True))
    op.add_column('Product', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.add_column('Product', sa.Column('status', sa.Enum('EFFECTIVE', 'DEFECT', 'IN_PROGRESS', name='productstatustypeenum'), nullable=True))
    op.add_column('Product', sa.Column('order_in', postgresql.UUID(), nullable=True))
    op.add_column('Product', sa.Column('decimal_number_id', postgresql.UUID(), nullable=True))
    op.add_column('Product', sa.Column('output_number', sa.VARCHAR(), nullable=True))
    op.add_column('Product', sa.Column('status_info', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'Product', 'Decimal_number', ['decimal_number_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Product', type_='foreignkey')
    op.drop_column('Product', 'status_info')
    op.drop_column('Product', 'output_number')
    op.drop_column('Product', 'decimal_number_id')
    op.drop_column('Product', 'order_in')
    op.drop_column('Product', 'status')
    op.drop_column('Product', 'sequence_number')
    op.drop_column('Product', 'pid')
    op.drop_column('Product', 'deleted_at')
    op.drop_column('Product', 'updated_at')
    op.drop_column('Product', 'created_at')
    op.drop_column('Decimal_number', 'name')
    # ### end Alembic commands ###
