"""Some changed field in Product model to nullable if value does not exist.

Revision ID: eaa425a0ee27
Revises: 13f48dce5c72
Create Date: 2023-07-17 13:16:34.977470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa425a0ee27'
down_revision = '13f48dce5c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
